#!/bin/bash`
PCIID=@GPU_BUS_ID@
PCIID=${PCIID/PCI:/}
source /etc/default/nvidia-fancontrol
while [ 1 = 1 ]; do
	curspd=$(nvidia-smi -q | grep GPU.*${PCIID/0:/00.} -A 48 | tail -n1 | awk '{print $4}')
	curtmp=$(nvidia-smi -q -d temperature | grep -A2 GPU.*${PCIID/0:/00.} | tail -n1 | awk '{print $5}')
	if [ $curtmp -gt ${TEMP_TARGET} ]; then
		let newspd="${curspd} + ${FAN_STEP}"
	else
		let newspd="${curspd} - ${FAN_STEP}"
	fi
	echo "${PCIID} Curspd: ${curspd} Curtmp: ${curtmp} NewSpd: ${newspd}" >> /var/log/nvidia-fancontrol.log
	nvidia-settings -a [gpu:0]/GPUFanControlState=1 -a [fan:0]/GPUTargetFanSpeed=${newspd}
	sleep 10
done
